Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  # =========================
  # Server
  # =========================
  config.vm.define "mel-haddS" do |server|

    server.vm.hostname = "mel-haddS"

    server.vm.network "private_network",
      ip: "192.168.56.110"

    server.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 1024
    end

    server.vm.provision "shell",
      path: "scripts/server.sh"
  end
end
